# Generated by Django 3.0.5 on 2020-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=15)),
                ('data_type', models.TextField()),
                ('default', models.CharField(max_length=15)),
                ('field_type', models.CharField(max_length=15)),
                ('field_type_label', models.TextField()),
                ('is_removable', models.BooleanField()),
                ('mandatory', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('entity', models.CharField(max_length=15)),
                ('customerId', models.IntegerField()),
                ('law', models.CharField(max_length=15)),
            ],
        ),
    ]
