# Generated by Django 3.0.5 on 2020-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20200926_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='customerId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='entity',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='template',
            name='law',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='template',
            table='template',
        ),
    ]
