# Generated by Django 3.0.5 on 2020-09-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_auto_20200926_1831'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='field',
            table='field',
        ),
    ]
